//! Web/TUI **wire contracts** — the provider-neutral DTOs the SPA and the
//! inspection plane consume over HTTP/WS.
//!
//! ts-rs is the source of truth: every type here derives [`ts_rs::TS`] with
//! `#[ts(export)]`, and the regenerated TypeScript is committed under
//! `contracts/generated/`. The drift test in `tests/contract_drift.rs`
//! re-exports into a clean temp dir and asserts byte-identity with the
//! committed files, so the "generated by ts-rs" header is genuinely true.
//!
//! Inline helper DTOs ([`entity::EntityHandle`], [`action::AvailableAction`])
//! are real Rust source types emitted inline via `#[ts(type = …)]` overrides;
//! they have no standalone binding but still trace every contract field to a
//! concrete Rust type.

pub mod action;
pub mod entity;
pub mod pulls;
pub mod repository;
pub mod review;
pub mod settings;
pub mod source;
pub mod tool_finder;
pub mod tool_fleet;
pub mod tool_registry;
pub mod web;

pub use action::AvailableAction;
pub use entity::EntityHandle;
pub use pulls::{
    AgentPosture, CheckPosture, IssueState, IssueSummary, MergePassport, MergePassportBlocker,
    MergePassportStatus, Mergeability, PullRequestDetail, PullRequestState, PullRequestSummary,
    ReviewPosture,
};
pub use repository::{
    CreateRepositoryPreview, CreateRepositoryRequest, DeleteRepositoryReceipt,
    DeleteRepositoryRequest, DeletedCount, JankuraiScoreListResponse, JankuraiScoreSummary,
    RepositoryFacets, RepositoryHostKind, RepositoryId, RepositoryListResponse,
    RepositoryMirrorStatus, RepositoryRole, RepositorySummary, RepositoryVisibility,
};
pub use review::{
    CreateReviewCommentRequest, ReviewComment, ReviewEvidence, ReviewSuggestion, ReviewThread,
    ReviewVerdict, SubmitReviewRequest,
};
pub use settings::{
    AccessSettings, AgentSettings, AuditSettings, BranchProtectionRule, CiSettings,
    FeatureSettings, GeneralSettings, MergeSettings, NotificationSettings, RepositorySettings,
    RetentionSettings, SecuritySettings, SettingsDiffPreview, SettingsFieldChange, SettingsPatch,
};
pub use source::{
    BlobEncoding, BlobResponse, MarkdownHeading, MarkdownLink, RefKind, RefSelectorItem,
    RenderedMarkdown, TreeEntry, TreeEntryKind,
};
pub use tool_finder::{
    ToolFinderCluster, ToolFinderDashboard, ToolFinderOccurrence, ToolFinderPatternFamily,
    ToolFinderProposeReceipt, ToolFinderScanMeta, ToolFinderScanStatus,
};
pub use tool_fleet::{ToolFleetEntry, ToolFleetResponse};
pub use tool_registry::{ToolRegistryEntry, ToolRegistrySummary};
pub use web::{
    ClientWsMessage, ServerWsMessage, SubscriptionSpec, Viewer, WebBootstrap, WebEvent,
    WebFeatureFlags,
};

use ts_rs::{Config, ExportError, TS};

/// The exported web/TUI wire contracts, in stable (sorted) order.
///
/// Each entry exports exactly one `contracts/generated/<Name>.ts` file. This
/// list is the single source the export binary and the drift test share, so
/// adding a contract here is the only place a new generated file is declared.
macro_rules! contract_exports {
    ($($ty:ty),+ $(,)?) => {
        /// Number of distinct contract types exported to `contracts/generated/`.
        pub const CONTRACT_COUNT: usize = { let mut n = 0; $( n += 1; let _ = stringify!($ty); )+ n };

        /// Export every web/TUI contract into the directory configured by `cfg`
        /// (`cfg.out_dir()`), one `<Name>.ts` file per type.
        ///
        /// Used by both the `export_contracts` binary (writing to the committed
        /// `contracts/generated/` tree) and the drift test (writing to a clean
        /// temp dir for byte-identity comparison).
        pub fn export_all_contracts(cfg: &Config) -> Result<(), ExportError> {
            $( <$ty as TS>::export(cfg)?; )+
            Ok(())
        }

        /// Returns the `(TypeName, generated-filename)` pairs for every contract,
        /// so callers (the drift test) can enumerate the expected output files.
        pub fn contract_files() -> Vec<(&'static str, String)> {
            let mut out = Vec::new();
            $(
                let path = <$ty as TS>::output_path()
                    .expect("every contract type is exportable");
                out.push((
                    stringify!($ty),
                    path.to_string_lossy().into_owned(),
                ));
            )+
            out
        }
    };
}

contract_exports!(
    AccessSettings,
    AgentPosture,
    AgentSettings,
    AuditSettings,
    BlobEncoding,
    BlobResponse,
    BranchProtectionRule,
    CheckPosture,
    CiSettings,
    ClientWsMessage,
    CreateRepositoryPreview,
    CreateRepositoryRequest,
    CreateReviewCommentRequest,
    DeleteRepositoryReceipt,
    DeleteRepositoryRequest,
    DeletedCount,
    FeatureSettings,
    GeneralSettings,
    IssueState,
    IssueSummary,
    JankuraiScoreListResponse,
    JankuraiScoreSummary,
    MarkdownHeading,
    MarkdownLink,
    MergePassport,
    MergePassportBlocker,
    MergePassportStatus,
    MergeSettings,
    Mergeability,
    NotificationSettings,
    PullRequestDetail,
    PullRequestState,
    PullRequestSummary,
    RefKind,
    RefSelectorItem,
    RenderedMarkdown,
    RepositoryFacets,
    RepositoryHostKind,
    RepositoryId,
    RepositoryListResponse,
    RepositoryMirrorStatus,
    RepositoryRole,
    RepositorySettings,
    RepositorySummary,
    RepositoryVisibility,
    RetentionSettings,
    ReviewComment,
    ReviewEvidence,
    ReviewPosture,
    ReviewSuggestion,
    ReviewThread,
    ReviewVerdict,
    SecuritySettings,
    ServerWsMessage,
    SettingsDiffPreview,
    SettingsFieldChange,
    SettingsPatch,
    SubmitReviewRequest,
    SubscriptionSpec,
    ToolFinderCluster,
    ToolFinderDashboard,
    ToolFinderOccurrence,
    ToolFinderPatternFamily,
    ToolFinderProposeReceipt,
    ToolFinderScanMeta,
    ToolFinderScanStatus,
    ToolFleetEntry,
    ToolFleetResponse,
    ToolRegistryEntry,
    ToolRegistrySummary,
    TreeEntry,
    TreeEntryKind,
    Viewer,
    WebBootstrap,
    WebEvent,
    WebFeatureFlags,
);
