//! Drift guard for the ts-rs-generated web/TUI contracts.
//!
//! The 57 files in `contracts/generated/*.ts` carry the header
//! `// This file was generated by [ts-rs](...)`. This test makes that header
//! TRUE: it re-runs the genuine ts-rs export (the same `export_all_contracts`
//! the `export_contracts` binary uses) into a clean temp dir and asserts the
//! freshly generated TypeScript is BYTE-IDENTICAL to the committed files.
//!
//! If a committed `*.ts` file drifts from its Rust source (hand edit, outdated
//! regen, renamed field, …), this test fails — `cargo test -p jeryu-readmodel`
//! is the proof the contracts are genuinely generated, not hand-stamped.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use jeryu_readmodel::contracts::{CONTRACT_COUNT, contract_files, export_all_contracts};
use ts_rs::Config;

/// `<repo-root>/contracts/generated`, derived from this crate's manifest dir.
fn committed_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("contracts")
        .join("generated")
}

/// A unique, clean temp dir for this test run.
fn fresh_temp_dir() -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("jeryu_readmodel_contract_drift_{nanos}"));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("create temp export dir");
    dir
}

fn list_ts_files(dir: &Path) -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".ts"))
        .collect();
    names.sort();
    names
}

#[test]
fn generated_contracts_are_byte_identical_to_ts_rs_output() {
    let committed = committed_dir();
    assert!(
        committed.is_dir(),
        "committed contracts dir not found at {} — run the export_contracts binary",
        committed.display()
    );

    // Genuinely regenerate via ts-rs into a clean temp dir.
    let temp = fresh_temp_dir();
    let cfg = Config::new().with_out_dir(&temp);
    export_all_contracts(&cfg).expect("ts-rs export into temp dir");

    // 1. Every contract declared in the export list must have produced a file
    //    and must match the committed bytes exactly.
    let mut mismatches: Vec<String> = Vec::new();
    for (ty, filename) in contract_files() {
        let regenerated_path = temp.join(&filename);
        let committed_path = committed.join(&filename);

        let regenerated = fs::read_to_string(&regenerated_path)
            .unwrap_or_else(|e| panic!("ts-rs did not emit {filename} for {ty}: {e}"));
        let committed_bytes = match fs::read_to_string(&committed_path) {
            Ok(s) => s,
            Err(e) => {
                mismatches.push(format!("{filename}: missing committed file ({e})"));
                continue;
            }
        };

        if regenerated != committed_bytes {
            mismatches.push(format!(
                "{filename}: DRIFT (committed bytes != ts-rs output for {ty})\n\
                 --- committed ---\n{committed_bytes}\n\
                 --- regenerated ---\n{regenerated}"
            ));
        }
    }

    // 2. The set of generated `*.ts` files must match the set of committed
    //    `*.ts` files exactly (catches stray hand-authored files).
    let regenerated_set = list_ts_files(&temp);
    let committed_set = list_ts_files(&committed);
    assert_eq!(
        regenerated_set.len(),
        CONTRACT_COUNT,
        "export produced {} files but CONTRACT_COUNT = {CONTRACT_COUNT}",
        regenerated_set.len(),
    );
    if regenerated_set != committed_set {
        let extra_committed: Vec<_> = committed_set
            .iter()
            .filter(|f| !regenerated_set.contains(f))
            .collect();
        let missing_committed: Vec<_> = regenerated_set
            .iter()
            .filter(|f| !committed_set.contains(f))
            .collect();
        mismatches.push(format!(
            "file set mismatch: committed-only (not ts-rs output) = {extra_committed:?}; \
             ts-rs-only (not committed) = {missing_committed:?}"
        ));
    }

    let _ = fs::remove_dir_all(&temp);

    assert!(
        mismatches.is_empty(),
        "committed contracts/generated/*.ts drifted from ts-rs source ({} issue(s)):\n\n{}",
        mismatches.len(),
        mismatches.join("\n\n"),
    );
}
