//! The [`EntityKind`] taxonomy and its display/route/badge mappings.

use serde::{Deserialize, Serialize};

/// Exhaustive taxonomy of control-plane entities.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum EntityKind {
    Fleet,
    RepoFamily,
    Repo,
    Branch,
    Commit,
    PullRequest,
    CiRun,
    CiRunBridge,
    Stage,
    Job,
    RunnerPool,
    RunnerManager,
    Runner,
    Node,
    CacheObject,
    CacheRequest,
    CacheVerdict,
    CacheTaint,
    TestPlan,
    TestCase,
    SelectorMiss,
    Agent,
    AgentSession,
    AgentTask,
    AgentRace,
    Bug,
    BugAttempt,
    GitRefUpdate,
    AdmissionDecision,
    CapabilityIntent,
    CapabilityGrant,
    JankuraiRun,
    JankuraiFinding,
    AerFinding,
    SecurityFinding,
    SecretAuthority,
    ReleaseSecretSet,
    Artifact,
    Signature,
    Sbom,
    ReleaseAttempt,
    ReleaseGate,
    Evidence,
    AuditEvent,
    LlmCall,
    Source,
    Action,
    Project,
    EvidenceCapsule,
    SecretAccess,
    Grant,
    Pool,
    System,
}

impl EntityKind {
    pub const ALL: &'static [Self] = &[
        Self::Fleet,
        Self::RepoFamily,
        Self::Repo,
        Self::Branch,
        Self::Commit,
        Self::PullRequest,
        Self::CiRun,
        Self::CiRunBridge,
        Self::Stage,
        Self::Job,
        Self::RunnerPool,
        Self::RunnerManager,
        Self::Runner,
        Self::Node,
        Self::CacheObject,
        Self::CacheRequest,
        Self::CacheVerdict,
        Self::CacheTaint,
        Self::TestPlan,
        Self::TestCase,
        Self::SelectorMiss,
        Self::Agent,
        Self::AgentSession,
        Self::AgentTask,
        Self::AgentRace,
        Self::Bug,
        Self::BugAttempt,
        Self::GitRefUpdate,
        Self::AdmissionDecision,
        Self::CapabilityIntent,
        Self::CapabilityGrant,
        Self::JankuraiRun,
        Self::JankuraiFinding,
        Self::AerFinding,
        Self::SecurityFinding,
        Self::SecretAuthority,
        Self::ReleaseSecretSet,
        Self::Artifact,
        Self::Signature,
        Self::Sbom,
        Self::ReleaseAttempt,
        Self::ReleaseGate,
        Self::Evidence,
        Self::AuditEvent,
        Self::LlmCall,
        Self::Source,
        Self::Action,
        Self::Project,
        Self::EvidenceCapsule,
        Self::SecretAccess,
        Self::Grant,
        Self::Pool,
        Self::System,
    ];

    pub fn label(self) -> &'static str {
        match self {
            Self::Fleet => "fleet",
            Self::RepoFamily => "repo_family",
            Self::Repo => "repo",
            Self::Branch => "branch",
            Self::Commit => "commit",
            Self::PullRequest => "pr",
            Self::CiRun => "ci_run",
            Self::CiRunBridge => "ci_run_bridge",
            Self::Stage => "stage",
            Self::Job => "job",
            Self::RunnerPool => "runner_pool",
            Self::RunnerManager => "runner_manager",
            Self::Runner => "runner",
            Self::Node => "node",
            Self::CacheObject => "cache_object",
            Self::CacheRequest => "cache_request",
            Self::CacheVerdict => "cache_verdict",
            Self::CacheTaint => "taint",
            Self::TestPlan => "test_plan",
            Self::TestCase => "test_case",
            Self::SelectorMiss => "selector_miss",
            Self::Agent => "agent",
            Self::AgentSession => "agent_session",
            Self::AgentTask => "agent_task",
            Self::AgentRace => "agent_race",
            Self::Bug => "bug",
            Self::BugAttempt => "bug_attempt",
            Self::GitRefUpdate => "git_ref_update",
            Self::AdmissionDecision => "admission_decision",
            Self::CapabilityIntent => "capability_intent",
            Self::CapabilityGrant => "capability_grant",
            Self::JankuraiRun => "jankurai_run",
            Self::JankuraiFinding => "jankurai_finding",
            Self::AerFinding => "aer_finding",
            Self::SecurityFinding => "security_finding",
            Self::SecretAuthority => "secret_authority",
            Self::ReleaseSecretSet => "release_secret_set",
            Self::Artifact => "artifact",
            Self::Signature => "signature",
            Self::Sbom => "sbom",
            Self::ReleaseAttempt => "release",
            Self::ReleaseGate => "gate",
            Self::Evidence => "evidence",
            Self::AuditEvent => "audit_event",
            Self::LlmCall => "llm_call",
            Self::Source => "source",
            Self::Action => "action",
            Self::Project => "project",
            Self::EvidenceCapsule => "capsule",
            Self::SecretAccess => "secret",
            Self::Grant => "grant",
            Self::Pool => "pool",
            Self::System => "system",
        }
    }

    pub fn route_segment(self) -> &'static str {
        match self {
            Self::PullRequest => "pull-requests",
            Self::EvidenceCapsule => "evidence-capsules",
            Self::ReleaseAttempt => "release-attempts",
            Self::ReleaseGate => "release-gates",
            Self::SecretAccess => "secret-access",
            Self::Pool => "pools",
            _ => self.label(),
        }
    }

    pub fn badge(self) -> &'static str {
        match self {
            Self::Fleet => "FLT",
            Self::RepoFamily => "FAM",
            Self::Repo | Self::Project => "REP",
            Self::Branch => "BR",
            Self::Commit => "SHA",
            Self::PullRequest => "PR",
            Self::CiRun | Self::CiRunBridge | Self::Stage => "CI",
            Self::Job => "JOB",
            Self::RunnerPool | Self::RunnerManager | Self::Runner | Self::Pool | Self::Node => {
                "RUN"
            }
            Self::CacheObject | Self::CacheRequest | Self::CacheVerdict | Self::CacheTaint => "CAC",
            Self::TestPlan | Self::TestCase | Self::SelectorMiss => "TST",
            Self::Agent | Self::AgentSession | Self::AgentTask | Self::AgentRace => "AGT",
            Self::Bug | Self::BugAttempt => "BUG",
            Self::GitRefUpdate | Self::AdmissionDecision => "GIT",
            Self::CapabilityIntent | Self::CapabilityGrant | Self::Grant => "CAP",
            Self::JankuraiRun | Self::JankuraiFinding => "JNK",
            Self::AerFinding => "AER",
            Self::SecurityFinding
            | Self::SecretAuthority
            | Self::ReleaseSecretSet
            | Self::SecretAccess => "SEC",
            Self::Artifact | Self::Signature | Self::Sbom => "ART",
            Self::ReleaseAttempt | Self::ReleaseGate => "REL",
            Self::Evidence | Self::EvidenceCapsule | Self::AuditEvent => "EVD",
            Self::LlmCall => "LLM",
            Self::Source => "SRC",
            Self::Action => "ACT",
            Self::System => "SYS",
        }
    }
}
