[package]
name = "jeryu-mirror-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "jeryu-mirror"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
jeryu-core = { path = "../jeryu-core" }
jeryu-gitd = { path = "../jeryu-gitd" }
jeryu-mirror = { path = "../jeryu-mirror" }
serde.workspace = true
serde_json.workspace = true
